keybinds:
  bindings:
    "Escape": "pauseMenu"
    "Space": "jump"
    "A": "walkLeft"
    "D": "walkRight"
    "E": "openInventory"
    "L-Ctrl": "sprint"
    "F11": "fullscreen"
    "L-Shift": "sneak"
    "F3": "debugInfo"
    "Q": "dropItem"
    "1": "hotbarSlot1"
    "2": "hotbarSlot2"
    "3": "hotbarSlot3"
    "S": "walkBackward"
    "4": "hotbarSlot4"
    "5": "hotbarSlot5"
    "6": "hotbarSlot6"
    "7": "hotbarSlot7"
    "W": "walkForward"
    "Enter": "chat"
    "8": "hotbarSlot8"
    "9": "hotbarSlot9"
resourcePack:
  name: "Default Pack"
  path: "resourcepacks/default"
  description: "Pack shipped with MineGDX."
  sizeMod: 1.0
servers: {}
playerName: ""
clientUUID: 0
language: "English"